services:
  - type: web
    name: luminus-api
    env: python
    buildCommand: bash render-build.sh
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
