services:
  - type: web
    name: luminus-api
    runtime: docker
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
